/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTenantRouteImport } from './routes/_authenticated/tenant'
import { Route as AuthenticatedLeasesIndexRouteImport } from './routes/_authenticated/leases.index'
import { Route as AuthenticatedLeasesLeaseIdRouteImport } from './routes/_authenticated/leases.$leaseId'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'
import { Route as AuthenticatedTenantIndexRouteImport } from './routes/_authenticated/tenant.index'
import { Route as AuthenticatedTenantLeaseRouteImport } from './routes/_authenticated/tenant.lease'
import { Route as AuthenticatedTenantMaintenanceRouteImport } from './routes/_authenticated/tenant.maintenance'
import { Route as AuthenticatedTenantPayRouteImport } from './routes/_authenticated/tenant.pay'
import { Route as AuthenticatedTenantTenancyRouteImport } from './routes/_authenticated/tenant.tenancy'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants.index'
import { Route as AuthenticatedTenantsTenancyIdRouteImport } from './routes/_authenticated/tenants.$tenancyId'
import { Route as AuthenticatedUnitsIndexRouteImport } from './routes/_authenticated/units.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantRoute = AuthenticatedTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeasesIndexRoute =
  AuthenticatedLeasesIndexRouteImport.update({
    id: '/leases/',
    path: '/leases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeasesLeaseIdRoute =
  AuthenticatedLeasesLeaseIdRouteImport.update({
    id: '/leases/$leaseId',
    path: '/leases/$leaseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantIndexRoute =
  AuthenticatedTenantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantLeaseRoute =
  AuthenticatedTenantLeaseRouteImport.update({
    id: '/lease',
    path: '/lease',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantMaintenanceRoute =
  AuthenticatedTenantMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantPayRoute = AuthenticatedTenantPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedTenantRoute,
} as any)
const AuthenticatedTenantTenancyRoute =
  AuthenticatedTenantTenancyRouteImport.update({
    id: '/tenancy',
    path: '/tenancy',
    getParentRoute: () => AuthenticatedTenantRoute,
  } as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantsTenancyIdRoute =
  AuthenticatedTenantsTenancyIdRouteImport.update({
    id: '/tenants/$tenancyId',
    path: '/tenants/$tenancyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitsIndexRoute = AuthenticatedUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenant': typeof AuthenticatedTenantRouteWithChildren
  '/leases/$leaseId': typeof AuthenticatedLeasesLeaseIdRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/tenant/maintenance': typeof AuthenticatedTenantMaintenanceRoute
  '/tenant/pay': typeof AuthenticatedTenantPayRoute
  '/tenant/tenancy': typeof AuthenticatedTenantTenancyRoute
  '/tenants/$tenancyId': typeof AuthenticatedTenantsTenancyIdRoute
  '/leases/': typeof AuthenticatedLeasesIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/tenant/': typeof AuthenticatedTenantIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/units/': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/leases/$leaseId': typeof AuthenticatedLeasesLeaseIdRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/tenant/maintenance': typeof AuthenticatedTenantMaintenanceRoute
  '/tenant/pay': typeof AuthenticatedTenantPayRoute
  '/tenant/tenancy': typeof AuthenticatedTenantTenancyRoute
  '/tenants/$tenancyId': typeof AuthenticatedTenantsTenancyIdRoute
  '/leases': typeof AuthenticatedLeasesIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/tenant': typeof AuthenticatedTenantIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/units': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenant': typeof AuthenticatedTenantRouteWithChildren
  '/_authenticated/leases/$leaseId': typeof AuthenticatedLeasesLeaseIdRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/tenant/lease': typeof AuthenticatedTenantLeaseRoute
  '/_authenticated/tenant/maintenance': typeof AuthenticatedTenantMaintenanceRoute
  '/_authenticated/tenant/pay': typeof AuthenticatedTenantPayRoute
  '/_authenticated/tenant/tenancy': typeof AuthenticatedTenantTenancyRoute
  '/_authenticated/tenants/$tenancyId': typeof AuthenticatedTenantsTenancyIdRoute
  '/_authenticated/leases/': typeof AuthenticatedLeasesIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/tenant/': typeof AuthenticatedTenantIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/units/': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/maintenance'
    | '/messages'
    | '/onboarding'
    | '/payments'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/tenant'
    | '/leases/$leaseId'
    | '/properties/$propertyId'
    | '/tenant/lease'
    | '/tenant/maintenance'
    | '/tenant/pay'
    | '/tenant/tenancy'
    | '/tenants/$tenancyId'
    | '/leases/'
    | '/properties/'
    | '/tenant/'
    | '/tenants/'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/documents'
    | '/maintenance'
    | '/messages'
    | '/onboarding'
    | '/payments'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/leases/$leaseId'
    | '/properties/$propertyId'
    | '/tenant/lease'
    | '/tenant/maintenance'
    | '/tenant/pay'
    | '/tenant/tenancy'
    | '/tenants/$tenancyId'
    | '/leases'
    | '/properties'
    | '/tenant'
    | '/tenants'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/maintenance'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/tenant'
    | '/_authenticated/leases/$leaseId'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/tenant/lease'
    | '/_authenticated/tenant/maintenance'
    | '/_authenticated/tenant/pay'
    | '/_authenticated/tenant/tenancy'
    | '/_authenticated/tenants/$tenancyId'
    | '/_authenticated/leases/'
    | '/_authenticated/properties/'
    | '/_authenticated/tenant/'
    | '/_authenticated/tenants/'
    | '/_authenticated/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant': {
      id: '/_authenticated/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof AuthenticatedTenantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leases/': {
      id: '/_authenticated/leases/'
      path: '/leases'
      fullPath: '/leases/'
      preLoaderRoute: typeof AuthenticatedLeasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leases/$leaseId': {
      id: '/_authenticated/leases/$leaseId'
      path: '/leases/$leaseId'
      fullPath: '/leases/$leaseId'
      preLoaderRoute: typeof AuthenticatedLeasesLeaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenant/': {
      id: '/_authenticated/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof AuthenticatedTenantIndexRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/lease': {
      id: '/_authenticated/tenant/lease'
      path: '/lease'
      fullPath: '/tenant/lease'
      preLoaderRoute: typeof AuthenticatedTenantLeaseRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/maintenance': {
      id: '/_authenticated/tenant/maintenance'
      path: '/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof AuthenticatedTenantMaintenanceRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/pay': {
      id: '/_authenticated/tenant/pay'
      path: '/pay'
      fullPath: '/tenant/pay'
      preLoaderRoute: typeof AuthenticatedTenantPayRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenant/tenancy': {
      id: '/_authenticated/tenant/tenancy'
      path: '/tenancy'
      fullPath: '/tenant/tenancy'
      preLoaderRoute: typeof AuthenticatedTenantTenancyRouteImport
      parentRoute: typeof AuthenticatedTenantRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$tenancyId': {
      id: '/_authenticated/tenants/$tenancyId'
      path: '/tenants/$tenancyId'
      fullPath: '/tenants/$tenancyId'
      preLoaderRoute: typeof AuthenticatedTenantsTenancyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units/': {
      id: '/_authenticated/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthenticatedUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTenantRouteChildren {
  AuthenticatedTenantLeaseRoute: typeof AuthenticatedTenantLeaseRoute
  AuthenticatedTenantMaintenanceRoute: typeof AuthenticatedTenantMaintenanceRoute
  AuthenticatedTenantPayRoute: typeof AuthenticatedTenantPayRoute
  AuthenticatedTenantTenancyRoute: typeof AuthenticatedTenantTenancyRoute
  AuthenticatedTenantIndexRoute: typeof AuthenticatedTenantIndexRoute
}

const AuthenticatedTenantRouteChildren: AuthenticatedTenantRouteChildren = {
  AuthenticatedTenantLeaseRoute: AuthenticatedTenantLeaseRoute,
  AuthenticatedTenantMaintenanceRoute: AuthenticatedTenantMaintenanceRoute,
  AuthenticatedTenantPayRoute: AuthenticatedTenantPayRoute,
  AuthenticatedTenantTenancyRoute: AuthenticatedTenantTenancyRoute,
  AuthenticatedTenantIndexRoute: AuthenticatedTenantIndexRoute,
}

const AuthenticatedTenantRouteWithChildren =
  AuthenticatedTenantRoute._addFileChildren(AuthenticatedTenantRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantRoute: typeof AuthenticatedTenantRouteWithChildren
  AuthenticatedLeasesLeaseIdRoute: typeof AuthenticatedLeasesLeaseIdRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedTenantsTenancyIdRoute: typeof AuthenticatedTenantsTenancyIdRoute
  AuthenticatedLeasesIndexRoute: typeof AuthenticatedLeasesIndexRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedUnitsIndexRoute: typeof AuthenticatedUnitsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantRoute: AuthenticatedTenantRouteWithChildren,
  AuthenticatedLeasesLeaseIdRoute: AuthenticatedLeasesLeaseIdRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedTenantsTenancyIdRoute: AuthenticatedTenantsTenancyIdRoute,
  AuthenticatedLeasesIndexRoute: AuthenticatedLeasesIndexRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedUnitsIndexRoute: AuthenticatedUnitsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
